In [3]:
import pandas as pd

<h2>Cheking data</h2>

In [4]:
df_merged = pd.read_csv("merged_weather_alarms.csv")

df_isw = pd.read_csv("isw_tfidf.csv")

df_telegram = pd.read_csv("telegram_tfidf.csv")

In [5]:
print("df_merged --> ", df_merged.shape)
print("df_isw --> ", df_isw.shape)
print("df_telegram --> ", df_telegram.shape)


print("Duplicates in df_merged datetime --> ", df_merged['datetime'].duplicated().sum())
print("Duplicates in df_isw datetime --> ", df_isw['datetime'].duplicated().sum())
print("Duplicates in df_telegram datetime --> ", df_telegram['datetime'].duplicated().sum())

df_merged -->  (808940, 31)
df_isw -->  (30264, 101)
df_telegram -->  (19557, 101)
Duplicates in df_merged datetime -->  773376
Duplicates in df_isw datetime -->  0
Duplicates in df_telegram datetime -->  0

In [6]:
df_merged.head(2)

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,region,hour,month,season,is_weekend,alarm,regions_in_alarm_now,alarms_last_24h,is_night,alarm_24h_ago
0,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.5,91.76,0.9,0.0,0.0,0.0,...,Вінницька,0,2,winter,0,0,0,0.0,1,0.0
1,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.4,89.80,0.6,0.0,0.0,0.0,...,Вінницька,1,2,winter,0,0,0,0.0,1,0.0

In [7]:
df_isw.head(2)

,isw_tfidf_1,isw_tfidf_2,isw_tfidf_3,isw_tfidf_4,isw_tfidf_5,isw_tfidf_6,isw_tfidf_7,isw_tfidf_8,isw_tfidf_9,isw_tfidf_10,...,isw_tfidf_92,isw_tfidf_93,isw_tfidf_94,isw_tfidf_95,isw_tfidf_96,isw_tfidf_97,isw_tfidf_98,isw_tfidf_99,isw_tfidf_100,datetime
0,0.366955,0.0,0.0,0.0,0.043097,0.0,0.244749,0.135634,0.100758,0.038909,...,0.020152,0.117193,0.069608,0.022746,0.20544,0.0,0.166083,0.0,0.0,2022-02-25 00:00:00
1,0.366955,0.0,0.0,0.0,0.043097,0.0,0.244749,0.135634,0.100758,0.038909,...,0.020152,0.117193,0.069608,0.022746,0.20544,0.0,0.166083,0.0,0.0,2022-02-25 01:00:00

In [8]:
df_telegram.head(2)

,tfidf_авіаційний,tfidf_авіаційний бомб,tfidf_авіаційний засіб,tfidf_авіація,tfidf_активність,tfidf_активність ворожий,tfidf_балістичного,tfidf_балістичного озброєння,tfidf_бомб,tfidf_бпла,...,tfidf_україна,tfidf_укриття,tfidf_ураження,tfidf_ураження прифронтовий,tfidf_харківщина,tfidf_харківщини,tfidf_ціль,tfidf_частина,tfidf_чернігівщини,datetime
0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-02-24 21:00:00
1,0.0,0.0,0.0,0.111461,0.0,0.0,0.0,0.0,0.0,0.0,...,0.172859,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-02-24 22:00:00

In [9]:
print(df_merged["datetime"].dtype)

print(df_isw["datetime"].dtype)

print(df_telegram["datetime"].dtype)

object
object
object

In [10]:
df_merged['datetime'] = pd.to_datetime(df_merged['datetime'])
df_isw['datetime'] = pd.to_datetime(df_isw['datetime'])
df_telegram['datetime'] = pd.to_datetime(df_telegram['datetime'])

print(df_merged["datetime"].dtype)
print(df_isw["datetime"].dtype)
print(df_telegram["datetime"].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]

In [11]:
isw_colums = [col for col in df_isw.columns if col != 'datetime']
df_isw[isw_colums] = df_isw[isw_colums].astype('float32')

telegram_colums = [col for col in df_telegram.columns if col != 'datetime']
df_telegram[telegram_colums] = df_telegram[telegram_colums].astype('float32')

In [12]:
print(df_isw.dtypes)
print(df_telegram.dtypes)

isw_tfidf_1             float32
isw_tfidf_2             float32
isw_tfidf_3             float32
isw_tfidf_4             float32
isw_tfidf_5             float32
                      ...
isw_tfidf_97            float32
isw_tfidf_98            float32
isw_tfidf_99            float32
isw_tfidf_100           float32
datetime         datetime64[ns]
Length: 101, dtype: object
tfidf_авіаційний                 float32
tfidf_авіаційний бомб            float32
tfidf_авіаційний засіб           float32
tfidf_авіація                    float32
tfidf_активність                 float32
                               ...
tfidf_харківщини                 float32
tfidf_ціль                       float32
tfidf_частина                    float32
tfidf_чернігівщини               float32
datetime                  datetime64[ns]
Length: 101, dtype: object

<h3>Merging isw data with weather and events</h3>

In [13]:
df = df_merged.merge(df_isw, on='datetime', how='left')

<h4>Cheking again</h4>

In [14]:
df.head(2)

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,isw_tfidf_91,isw_tfidf_92,isw_tfidf_93,isw_tfidf_94,isw_tfidf_95,isw_tfidf_96,isw_tfidf_97,isw_tfidf_98,isw_tfidf_99,isw_tfidf_100
0,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.5,91.76,0.9,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.4,89.80,0.6,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.shape

(808940, 131)

In [16]:
df.isna().sum().sum()

np.int64(12215900)

In [17]:
isw_colums = [c for c in df.columns if c.startswith('isw_tfidf_')]
df[isw_colums] = df[isw_colums].fillna(0)

df.isna().sum().sum()

np.int64(0)

In [18]:
df.to_csv('100-isw-weather-events.csv', index=False)

<h2>Merging telegram</h2>

<h3>Shifting hour</h3>

In [19]:
df_telegram['datetime'] = pd.to_datetime(df_telegram['datetime']) + pd.Timedelta(hours=1)

In [20]:
df_telegram.head(2)

,tfidf_авіаційний,tfidf_авіаційний бомб,tfidf_авіаційний засіб,tfidf_авіація,tfidf_активність,tfidf_активність ворожий,tfidf_балістичного,tfidf_балістичного озброєння,tfidf_бомб,tfidf_бпла,...,tfidf_україна,tfidf_укриття,tfidf_ураження,tfidf_ураження прифронтовий,tfidf_харківщина,tfidf_харківщини,tfidf_ціль,tfidf_частина,tfidf_чернігівщини,datetime
0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-02-24 22:00:00
1,0.0,0.0,0.0,0.111461,0.0,0.0,0.0,0.0,0.0,0.0,...,0.172859,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-02-24 23:00:00

In [21]:
completed_df = df.merge(df_telegram, on='datetime', how='left')

<h4>Cheking again</h4>

In [22]:
completed_df

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,tfidf_ударний бпла,tfidf_україна,tfidf_укриття,tfidf_ураження,tfidf_ураження прифронтовий,tfidf_харківщина,tfidf_харківщини,tfidf_ціль,tfidf_частина,tfidf_чернігівщини
0,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.5,91.76,0.9,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.4,89.80,0.6,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,49.2336,28.4486,"Vinnytsia,Ukraine",2.0,-0.3,90.44,0.6,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49.2336,28.4486,"Vinnytsia,Ukraine",1.9,-0.3,91.75,0.7,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,49.2336,28.4486,"Vinnytsia,Ukraine",1.8,-0.2,92.40,0.7,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808935,51.4937,31.2944,"Chernihiv,Ukraine",5.8,4.6,62.55,-0.8,0.0,0.0,0.0,...,0.0,0.0,0.0,0.183628,0.23228,0.000000,0.0,0.0,0.0,0.0
808936,51.4937,31.2944,"Chernihiv,Ukraine",5.0,3.3,65.16,-1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.00000,0.431394,0.0,0.0,0.0,0.0
808937,51.4937,31.2944,"Chernihiv,Ukraine",3.9,2.0,69.86,-1.1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0
808938,51.4937,31.2944,"Chernihiv,Ukraine",3.0,1.0,76.65,-0.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0
808939,51.4937,31.2944,"Chernihiv,Ukraine",2.1,0.3,83.52,-0.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0

In [24]:
completed_df.shape

(808940, 231)

In [ ]:
completed_df.isna().sum().sum()

In [78]:
tg_colums = [c for c in completed_df.columns if c.startswith('tfidf_')]
completed_df[tg_colums] = completed_df[tg_colums].fillna(0)

In [79]:
completed_df.isna().sum().sum()

np.int64(0)

In [80]:
completed_df.isna().sum()

city_latitude         0
city_longitude        0
city_address          0
hour_temp             0
hour_feelslike        0
                     ..
tfidf_харківщина      0
tfidf_харківщини      0
tfidf_ціль            0
tfidf_частина         0
tfidf_чернігівщини    0
Length: 231, dtype: int64

In [81]:
completed_df.head()

,city_latitude,city_longitude,city_address,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,...,tfidf_ударний бпла,tfidf_україна,tfidf_укриття,tfidf_ураження,tfidf_ураження прифронтовий,tfidf_харківщина,tfidf_харківщини,tfidf_ціль,tfidf_частина,tfidf_чернігівщини
0,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.5,91.76,0.9,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,49.2336,28.4486,"Vinnytsia,Ukraine",2.1,-0.4,89.80,0.6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,49.2336,28.4486,"Vinnytsia,Ukraine",2.0,-0.3,90.44,0.6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,49.2336,28.4486,"Vinnytsia,Ukraine",1.9,-0.3,91.75,0.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,49.2336,28.4486,"Vinnytsia,Ukraine",1.8,-0.2,92.40,0.7,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
completed_df.to_csv('data_for_ML-tgShifted.csv', index=False)

In [83]:
completed_df.to_parquet('data_for_ML-tgShifted.parquet', index=False)